services:
    - postgresql
before_script:
    # - psql -U postgres -c 'CREATE DATABASE pgapp_test;'
    - psql -d pgapp_test -U postgres -f db/migrate/20170526114520_create_posts.rb

script:
    - bundle exec rspec
