development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:bcaccfa2cd34fd82abdbf770a1ac4760@porgy.redistogo.com:11833/
  channel_prefix: acebook_production
